# Don't print new line at start of prompt
add_newline = true

[directory]
truncation_length = 3
truncation_symbol = "./"

[time]
disabled = false

[hostname]
ssh_only = false
disabled = false
format= "on [$hostname](red) "

[username]
show_always = true

[character]
success_symbol = "[âœ](bold green)"

[kubernetes]
format = 'on [â›µ $context \($namespace\)](dimmed green) '
disabled = false

[golang]
#format = "via [î˜¦ $version]"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 20
truncation_symbol = ".."
